### PR TITLE
add dependency libbsd

### PR DESCRIPTION
**Pull request by nato-re**
I had the same problem as Kaddate in [the comments on AUR package](https://aur.archlinux.org/packages/android-studio#comment-989477). I also never contributed before, so that's the changes I think would be necessary to add this dependency. I would really enjoy your feedback.

### CODE REVIEW

**Comment by nato-re** [comment]
@SailReal or @kordianbruck, do you think it is valid?

**Comment by SailReal** [comment]
Thanks for your PR and sorry for the late reaction.

Hmm I'm not sure, if I do an 

* `ldd /home/julian/tools/android/emulator/qemu/linux-x86_64/qemu-system-x86_64` or
* `ldd /home/julian/tools/android/emulator/emulator`
 
`libbsd` is not listed there. If you execute `ldd`, do you see the library listed there?

Wherever `libbsd` is installed on my system and required for some other packages so I can not simply remove it and try to run the emulator.

**Comment by nato-re** [comment]
Thanks for the reply, man! Going through this `ldd` inspection, I get this:
```sh
$ ldd Android/Sdk/emulator/emulator 
        linux-vdso.so.1 (0x00007c559fe0f000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007c559fb4d000)
        libandroid-emu-protos.so => /home/nato/Android/Sdk/emulator/lib64/libandroid-emu-protos.so (0x00007c559fa85000)
        libandroid-emu-metrics.so => /home/nato/Android/Sdk/emulator/lib64/libandroid-emu-metrics.so (0x00007c559f800000)
        libandroid-emu-curl.so => /home/nato/Android/Sdk/emulator/lib64/libandroid-emu-curl.so (0x00007c559f400000)
        libandroid-emu-agents.so => /home/nato/Android/Sdk/emulator/lib64/libandroid-emu-agents.so (0x00007c559fa7f000)
        libc++.so.1 => /home/nato/Android/Sdk/emulator/lib64/libc++.so.1 (0x00007c559f6c3000)
        libandroid-emu-base-logging.so => /home/nato/Android/Sdk/emulator/lib64/libandroid-emu-base-logging.so (0x00007c559fa6f000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007c559fa6a000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007c559fa65000)
        libglib2_linux-x86_64.so => /home/nato/Android/Sdk/emulator/lib64/libglib2_linux-x86_64.so (0x00007c559f2c1000)
        libprotobuf.so.26.2.0 => /home/nato/Android/Sdk/emulator/lib64/libprotobuf.so.26.2.0 (0x00007c559f000000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007c559fa5e000)
        libabseil_dll.so => /home/nato/Android/Sdk/emulator/lib64/libabseil_dll.so (0x00007c559ef32000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007c559ee43000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007c559f695000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007c559ec52000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007c559f296000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007c559fe11000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007c559fa57000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007c559f68d000)
        
$ ldd Android/Sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64 
        linux-vdso.so.1 (0x000074657004f000)
        libtcmalloc_minimal.so.4 => /usr/lib/libtcmalloc_minimal.so.4 (0x000074656dc2a000)
        libutil.so.1 => /usr/lib/libutil.so.1 (0x0000746570017000)
        libandroid-emu-tracing.so => not found
        libandroid-webrtc.so => not found
        libpulse.so.0 => /usr/lib/libpulse.so.0 (0x000074656dbd5000)
        libQt6WebChannelAndroidEmu.so.6 => not found
        libQt6WebEngineWidgetsAndroidEmu.so.6 => not found
        libQt6WebSocketsAndroidEmu.so.6 => not found
        libQt6NetworkAndroidEmu.so.6 => not found
        libQt6WebEngineCoreAndroidEmu.so.6 => not found
        libQt6SvgAndroidEmu.so.6 => not found
        libemugl_common.so => not found
        libQt6SvgWidgetsAndroidEmu.so.6 => not found
        libc++.so.1 => not found
        libandroid-emu-metrics.so => not found
        libglib2_linux-x86_64.so => not found
        librt.so.1 => /usr/lib/librt.so.1 (0x000074657000c000)
        libm.so.6 => /usr/lib/libm.so.6 (0x000074656dae6000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x0000746570007000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x0000746570002000)
        libandroid-emu-curl.so => not found
        libandroid-emu-protos.so => not found
        libprotobuf.so.26.2.0 => not found
        libandroid-emu-agents.so => not found
        libandroid-emu-base-logging.so => not found
        libabseil_dll.so => not found
        libX11.so.6 => /usr/lib/libX11.so.6 (0x000074656d9a5000)
        libQt6WidgetsAndroidEmu.so.6 => not found
        libQt6CoreAndroidEmu.so.6 => not found
        libQt6GuiAndroidEmu.so.6 => not found
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x000074656d977000)
        libc.so.6 => /usr/lib/libc.so.6 (0x000074656d786000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x0000746570051000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x000074656d400000)
        libpulsecommon-17.0.so => /usr/lib/pulseaudio/libpulsecommon-17.0.so (0x000074656d6ff000)
        libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x000074656d6ae000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x000074656d3d5000)
        libsndfile.so.1 => /usr/lib/libsndfile.so.1 (0x000074656d34e000)
        libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x000074656d25a000)
        libasyncns.so.0 => /usr/lib/libasyncns.so.0 (0x000074656fff2000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x000074656ffed000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x000074656ffe5000)
        libogg.so.0 => /usr/lib/libogg.so.0 (0x000074656d6a4000)
        libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x000074656d1af000)
        libFLAC.so.12 => /usr/lib/libFLAC.so.12 (0x000074656d16b000)
        libopus.so.0 => /usr/lib/libopus.so.0 (0x000074656cc00000)
        libmpg123.so.0 => /usr/lib/libmpg123.so.0 (0x000074656cba4000)
        libmp3lame.so.0 => /usr/lib/libmp3lame.so.0 (0x000074656cb2d000)
        libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x000074656d13d000)
        libcap.so.2 => /usr/lib/libcap.so.2 (0x000074656d698000)
```

When I uninstall the `libssd` and try to run the standard phone on android studio GUI, it throws an error `The emulator process for AVD Medium_Phone_API_35 has terminated.`.
Then when I look at the `idea.log` I find this:
```
2024-11-04 11:01:03,651 [  10227]   INFO - #com.android.adblib.impl.services.TrackDevicesService - "host:track-devices-proto-binary" - opening connection to ADB server, timeout: 4,999.0 msec remaining, 0.0 msec elapsed
2024-11-04 11:01:04,585 [  11161]   INFO - Emulator: Medium Phone API 35 - /home/nato/Android/Sdk/emulator/emulator -netdelay none -netspeed full -avd Medium_Phone_API_35
2024-11-04 11:01:04,591 [  11167]   INFO - Emulator: Medium Phone API 35 - Android emulator version 35.2.10.0 (build_id 12414864) (CL:N/A)
2024-11-04 11:01:04,591 [  11167]   INFO - Emulator: Medium Phone API 35 - Graphics backend: gfxstream
2024-11-04 11:01:04,591 [  11167]   INFO - Emulator: Medium Phone API 35 - Found systemPath /home/nato/Android/Sdk/system-images/android-35/google_apis_playstore/x86_64/
2024-11-04 11:01:04,607 [  11183]   INFO - Emulator: Medium Phone API 35 - /home/nato/Android/Sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory
2024-11-04 11:01:04,608 [  11184]   INFO - Emulator: Medium Phone API 35 - Process finished with exit code 127
2024-11-04 11:01:04,608 [  11184]   WARN - Emulator: Medium Phone API 35 - Emulator terminated with exit code 127
2024-11-04 11:01:05,595 [  12171]   WARN - #com.android.sdklib.deviceprovisioner.DeviceAction - The emulator process for AVD Medium_Phone_API_35 has terminated.
com.android.tools.idea.avdmanager.EmulatorConnectionListener$EmulatorTerminatedException: The emulator process for AVD Medium_Phone_API_35 has terminated.
        at com.android.tools.idea.avdmanager.EmulatorConnectionListener$WaitForEmulatorTask.run(EmulatorConnectionListener.java:93)
        at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:134)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

When I install the `libssd` again with yay, the emulator runs again without a problem.

**Comment by SailReal** [comment]
I highly assume this is an upstream bug, created https://issuetracker.google.com/issues/377131186

**Comment by nato-re** [comment]
okay, this looks right, closing the PR, thank you!

**Pull request closed without merging**
