### PR TITLE
Giraffe 2022.3.1.18

### PR DESCRIPTION
**Pull request by Dhina17**

### CODE REVIEW

**Comment by Dhina17** [comment]
hold.

**Comment by Dhina17** [comment]
Kotlin plugin crashes https://p.lineageos.org/kjNCYLg8yB

**Comment by Dhina17** [comment]
@SailReal I tried to start the studio from the official release . same issue. seems like google broke it. Maybe we have to wait for the hotfix. Please check from your side if you get some time

**Comment by SailReal** [comment]
Thanks for letting me know :+1: . Yes, will have a look as well on it

**Comment by Dhina17** [comment]
@SailReal It works after a clean install. might be a problem from my side configuration. Better check from your once and merge if it's ok. Thanks

**Review by SailReal — APPROVED** [review]
Sorry for the delay in looking into this release.
Your update works on my device so merging and lets hope the best :blush:

**Pull request merged**
