### PR TITLE
Update to 2023.1.1.26

### PR DESCRIPTION
**Pull request by furai**
Update to the latest stable release Hedgehog 2023.1.1.26.

EDIT: I've tested it now on 2 machines with completely different hardware and it worked without problems.

### CODE REVIEW

**Comment by SailReal** [comment]
Interesting, I updated it as well but getting crashes on startup with 

```
Internal error. Please refer to https://code.google.com/p/android/issues

com.intellij.diagnostic.PluginException: Key com.google.gct.idea.appengine.admin.AppEngineAdminService duplicated; existingAdapter: ServiceAdapter(descriptor=ServiceDescriptor(interface='com.google.gct.idea.appengine.admin.AppEngineAdminService', serviceImplementation='com.google.gct.idea.appengine.admin.GoogleApiClientAppEngineAdminService', testServiceImplementation='null', headlessImplementation='null', overrides=false, configurationSchemaKey='null', preload=FALSE, client=null), pluginDescriptor=PluginDescriptor(name=Google Cloud Tools For Android Studio, id=com.google.gct, descriptorPath=plugin.xml, path=/opt/android-studio/plugins/google-cloud-tools-as, version=231.9392.1.2311.11076708, package=null, isBundled=true)); descriptor: com.google.gct.idea.appengine.admin.GoogleApiClientAppEngineAdminService; app: Application (containerState PRE_INIT) ; current plugin: com.google.gct.core
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:588)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:293)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:46)
    at com.intellij.idea.ApplicationLoader.doInitApplication(ApplicationLoader.kt:86)
    at com.intellij.idea.ApplicationLoader.access$doInitApplication(ApplicationLoader.kt:1)
    at com.intellij.idea.ApplicationLoader$doInitApplication$1.invokeSuspend(ApplicationLoader.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:63)
    at com.intellij.idea.MainImpl.start(MainImpl.kt:12)
    at com.intellij.idea.StartupUtil$startApplication$7.invokeSuspend(StartupUtil.kt:297)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at com.intellij.idea.Main.main(Main.kt:40)

-----
Your JRE: 17.0.7+0-17.0.7b1000.6-10550314 amd64 (JetBrains s.r.o.)
/opt/android-studio/jbr
```

so I assumened there is still a problem with this version but when you do not get that it is maybe a problem in my setup? Will have a look in it and try also on a clean device.

**Comment by furai** [comment]
According to google's tracker it's the issue stemming from borked installation. Easiest way to correct it is to do fresh install. Maybe after all they need to iron some things out. Overall it works here but let's wait for others to test it.

https://developer.android.com/studio/known-issues some posts here suggest removing caches/configs.

https://issuetracker.google.com/issues/300760564

Seems like some general issue with upgrade rather than the android studio itself.

EDIT: Seems like this might be an issue of using makpkg in the same directory as previous build. The build artefacfs from previous build were there in pkg folder and new release was probably extracted on top of that concatting the folders from which install tar.gz file was made. This resulted in creating duplicates, probably some plugin changed name.. It's probably enough to do `makepkg -c` to clean. Though I'm not sure as I can't reproduce.

**Comment by SailReal** [comment]
@furai is right, cleaning up the build folder and rebuilding did the trick, so from my point of view we can release it because it shouldn't happen often on user devices and the workaround is really simple.

**Comment by SailReal** [comment]
Ah and thank you! :slightly_smiling_face:

**Pull request merged**
